### ISSUE TITLE
Trainer.py error

### ISSUE THREAD

**Issue by smithee771** [duskvirkus/alias-free-gan-pytorch-lightning#39]
Hi, first of all many thanks for the repo.
I'm trying to run in Colab:

!python /content/drive/MyDrive/colab-alias-free-gan/alias-free-gan/scripts/trainer.py --help

and I'm getting this error:

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/decorators.py:17: LightningDeprecationWarning: Using `pytorch_lightning.core.decorators.parameter_validation` is deprecated in v1.5, and will be removed in v1.7. It has been replaced by automatic parameters tying with `pytorch_lightning.utilities.params_tying.set_shared_parameters`
  "Using `pytorch_lightning.core.decorators.parameter_validation` is deprecated in v1.5, "
Traceback (most recent call last):
  File "/content/drive/MyDrive/colab-alias-free-gan/alias-free-gan/scripts/trainer.py", line 19, in <module>
    from src.alias_free_gan import AliasFreeGAN
  File "/content/drive/MyDrive/colab-alias-free-gan/alias-free-gan/scripts/../src/alias_free_gan.py", line 18, in <module>
    from src.model import Generator, filter_parameters
  File "/content/drive/MyDrive/colab-alias-free-gan/alias-free-gan/scripts/../src/model.py", line 11, in <module>
    from src.stylegan2.model import PixelNorm, EqualLinear, EqualConv2d
  File "/content/drive/MyDrive/colab-alias-free-gan/alias-free-gan/scripts/../src/stylegan2/model.py", line 18, in <module>
    from pytorch_lightning.core.decorators import auto_move_data
ImportError: cannot import name 'auto_move_data' from 'pytorch_lightning.core.decorators' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/decorators.py)

Is it a bug? any hint?
many thanks in advance :)

**Comment by polimorfo** [comment]
Same here, after 2 weeks of a flawless training period, yesterday the same error was thrown.

**Comment by duskvirkus** [comment]
@smithee77 @polimorfo Sorry for the delayed response use pytorch-lightning==1.4.9 when installing. I'll try to update the requirements file.

**Comment by polimorfo** [comment]
As easy as that,, Thank you @duskvirkus !
